---
title: "DS6373 Final Project"
author: "Eric Graham"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tswge)
library(vars)
library(nnfor)
library(fredr)
library(quantmod)
library(tidyverse)
library(lubridate)
library(lmtest)
```

## Load Data

### Response

```{r}
fredr_set_key(Sys.getenv("FRED_API_KEY"))

start_date = as.Date("1995-01-01")
end_date = Sys.Date()

sp500 = getSymbols("^GSPC", from = start_date, to = end_date, auto.assign = FALSE)
sp500_monthly = to.monthly(sp500, OHLC = FALSE)
log_returns = diff(log(Cl(sp500_monthly)))
log_returns = na.omit(log_returns)

sp500_df = data.frame(
  date = as.Date(index(log_returns)),
  sp500_log_return = as.numeric(log_returns)
)
sp500_df$date = floor_date(sp500_df$date, "month") + months(1) - days(1)
```

### Predictors

```{r}
aggregate_to_monthly = function(df, value_col = "value") {
  df %>%
    mutate(month = floor_date(date, "month")) %>%
    group_by(month) %>%
    summarize(value = mean(get(value_col), na.rm = TRUE), .groups = "drop") %>%
    mutate(date = month + months(1) - days(1)) %>%
    select(date, value)
}

term_spread = fredr(series_id = "T10Y2Y", observation_start = start_date, observation_end = end_date) %>%
  aggregate_to_monthly() %>%
  rename(term_spread = value)

baa = fredr(series_id = "DBAA", observation_start = start_date, observation_end = end_date) %>%
  aggregate_to_monthly() %>%
  rename(baa = value)

dgs10 = fredr(series_id = "DGS10", observation_start = start_date, observation_end = end_date) %>%
  aggregate_to_monthly() %>%
  rename(dgs10 = value)

vix = fredr(series_id = "VIXCLS", observation_start = start_date, observation_end = end_date) %>%
  aggregate_to_monthly() %>%
  rename(vix = value)

predictors = term_spread %>%
  full_join(baa, by = "date") %>%
  full_join(dgs10, by = "date") %>%
  full_join(vix, by = "date") %>%
  mutate(credit_spread = baa - dgs10) %>%
  select(date, term_spread, credit_spread, vix)
```

### Combined DF

```{r}
df = inner_join(sp500_df, predictors, by = "date") %>%
  arrange(date) %>%
  na.omit()

str(df)
head(df)
tail(df)
dim(df)
```

### Missingness Check

```{r}
summary(df)

colSums(is.na(df))

sum(is.na(df))

anyNA(df)

df[!complete.cases(df), ]
```

## Stationarity

```{r}
plotts.sample.wge(df$sp500_log_return)
plotts.sample.wge(df$term_spread)
plotts.sample.wge(df$credit_spread)
plotts.sample.wge(df$vix)
```

```{r}
diff_term = artrans.wge(df$term_spread, phi.tr = 1)
plotts.sample.wge(diff_term)
parzen.wge(diff_term)
acf(diff_term)
```

```{r}
diff_credit = artrans.wge(df$credit_spread, phi.tr = 1)
plotts.sample.wge(diff_credit)
parzen.wge(diff_credit)
acf(diff_credit)
```

```{r}
diff_vix = artrans.wge(df$vix, phi.tr = 1)
plotts.sample.wge(diff_vix)
parzen.wge(diff_vix)
acf(diff_vix)
```

```{r}
df$diff_term = c(NA, diff_term)
df$diff_credit = c(NA, diff_credit)
df$diff_vix = c(NA, diff_vix)
```

```{r}
head(df)
```

